= Github Action Orchestrator - EXPERIMENTAL

Kotlin Scripts to manage GitHub Action Runners on self-hosted machines

NOTE: As Kotlin Scripting support is still highly experimental there is no guarantee that this works on your machine.

Scripts have been developed against Kotlin 1.3.72.

== Setup

You need to create a GitHub personal access token with repo permissions and set it as environment variable in your system: `GITHUB_ACTIONS_RUNNER_REGISTRATION_TOKEN={token}`

== How to use and add a repository?

Edit the script and add the desired *organization* and *repository names* that you want to setup.

Then just run the orchestrator: `./github-action-orchestrator.main.kts`

It will create a new folder `github-runners` where all repository runners could be found. Every mentioned runner will be configured as a service.

== Hot to remove a repository?

In case you want to remove one of the repository runners just move the entry to the `reposToRemove` and execute the script. It will unregister the runner for that repo and delete all remaining files.

You might remove that from the the script file.


== ToDos

* configuration should be stored as file
* script accepts arguments to *add* and *remove* repositories

== Inspired by:

* link:https://github.com/Kotlin/kotlin-script-examples[Kotlin scripting examples using `kotlin-main-kts`]
* link:https://github.com/jakubriegel/kotlin-shell[Kotlin Shell]
* Blog post link:https://dev.to/wayofthepie/ephemeral-self-hosted-github-actions-runners-1h5m[Ephemeral Self-Hosted Github Actions Runners]
